version: '3'

services:

  rest-app:
    container_name: rest-app
    build:
      context: rest-app
      dockerfile: Dockerfile
    image: mockbank/rest-app:latest
    ports:
      - "8090:8090"
    networks:
      - api

  web-app:
    container_name: web-app
    build:
      context: web-app
      dockerfile: Dockerfile
    image: mockbank/web-app:latest
    ports:
      - "8080:8080"
    environment:
      - base_url=mockbank://rest-app:8090
    networks:
      - api
    depends_on:
      -  rest-app

networks:
  api:
    driver: bridge