services:

  rest-app:
    container_name: mockbank-rest
    build:
      context: rest-app
      dockerfile: Dockerfile
    image: valvikx/mockbank-rest:latest
    ports:
      - "8090:8090"
    networks:
      - mockbank-net

  web-app:
    container_name: mockbank-web
    build:
      context: web-app
      dockerfile: Dockerfile
    image: valvikx/mockbank-web:latest
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://mockbank-rest:8090
    networks:
      - mockbank-net
    depends_on:
      - rest-app

networks:
  mockbank-net: