DROP TABLE IF EXISTS BANK_ACCOUNT;
DROP TABLE IF EXISTS CREDIT_CARD;
CREATE TABLE BANK_ACCOUNT
(
    ACCOUNT_ID        INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER    VARCHAR(34)  NOT NULL UNIQUE,
    CUSTOMER          VARCHAR(128) NOT NULL,
    REGISTRATION_DATE DATE         NOT NULL
);
CREATE TABLE CREDIT_CARD
(
    CARD_ID         INT AUTO_INCREMENT PRIMARY KEY,
    CARD_NUMBER     VARCHAR(16) NOT NULL UNIQUE,
    EXPIRATION_DATE DATE        NOT NULL,
    BALANCE         DECIMAL(6, 2) NOT NULL DEFAULT 0,
    ACCOUNT_ID      INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES BANK_ACCOUNT (ACCOUNT_ID)
);