spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /
  profiles:
    active: ${dbprofile:prod-db}
  output:
    ansi:
      enabled: always

server:
  port: ${port:8090}

springdoc:
  swagger-ui:
    operations-sorter: method
    use-root-path: true
  cache:
    disabled: true