spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /
  profiles:
    active: ${dbprofile:prod-db}

server:
  port: ${port:8090}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    use-root-path: true
  cache:
    disabled: true