GET http://localhost:8090/api/accounts
Accept: application/json
###
POST http://localhost:8090/api/accounts
Content-Type: application/json

{
  "numberPattern": "BY 99T6",
  "customerPattern": "an ov"
}
###
POST http://localhost:8090/api/accounts
Content-Type: application/json

{
  "customerPattern": "ov"
}
###
POST http://localhost:8090/api/accounts
Content-Type: application/json

{
  "numberPattern": "BY"
}