GET http://localhost:8090/accounts
Accept: application/json
###
POST http://localhost:8090/accounts
Content-Type: application/json

{
  "numberPattern": "TQ99IK",
  "customerPattern": "Sergeev"
}
###
POST http://localhost:8090/accounts
Content-Type: application/json

{
  "customerPattern": "Ivan"
}
###
POST http://localhost:8090/accounts
Content-Type: application/json

{
  "numberPattern": "BY"
}