GET http://localhost:8090/api/account
Accept: application/json
###
GET http://localhost:8090/api/account/1
Accept: application/json
###
GET http://localhost:8090/api/account/1/cards
Accept: application/json
###
POST http://localhost:8090/api/account
Content-Type: application/json

{
  "customer": "Sidor Sidorov"
}
###
PUT http://localhost:8090/api/account
Content-Type: application/json

{
  "id": 1,
  "customer": "Ivan Ivanoff"
}
###
DELETE http://localhost:8090/api/account/1
Content-Type: application/json