GET http://localhost:8090/api/card/1
Accept: application/json
###
GET http://localhost:8090/api/card/1/deposit
Accept: application/json
###
GET http://localhost:8090/api/card/1/transfer
Accept: application/json
###
POST http://localhost:8090/api/card
Content-Type: application/json

1
###
POST http://localhost:8090/api/card/deposit
Content-Type: application/json

{
  "targetCardNumber": "4000003394112581",
  "valueSumOfMoney": "1000,55",
  "locale": "ru"
}
###
POST http://localhost:8090/api/card/deposit
Content-Type: application/json

{
  "targetCardNumber": "4000003394112581",
  "valueSumOfMoney": "1000.55",
  "locale": "en"
}
###
POST http://localhost:8090/api/card/transfer
Content-Type: application/json

{
  "sourceCardNumber": "4000003394112581",
  "targetCardNumber": "4000002538269224",
  "valueSumOfMoney": "1000,6",
  "locale": "ru"
}
###
DELETE http://localhost:8090/api/card/1
Accept: application/json